In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

import tensorflow as tf 

from decimal import  Decimal
# import torch

In [3]:
# data.to_pickle("./Data/pickled_TrainingData")
# data = pd.read_csv("./Data/TrainingData.csv")
data = pd.read_pickle("./Data/pickled_TrainingData")
data.head(10)

CID                                               Text  class
0    0  3fa9e6ac4a36c66b8ca3887914c6c75b08dad9095f1d7a...      3
1    1  21b7f56f644f02d51ae82c9d50f69fad686319657712d4...      2
2    2  74203af11b8bbb1d31ac34e85f3076588fbbf2dcf1a4f7...      3
3    3  6b412e99f1dea02c124a90b5f2cf29496cb84f2b2b33a0...      1
4    4  5b84fb6fc7710b0e499394d9b406950d2436a118e2d867...      1
5    5  100c868cab4e21cbdd559c593b2bf54cdbf54c5ed0223f...      1
6    6  2b087feb3a6cff5c4811a7eff6e9024a761ef4b07f74f8...      3
7    7  4bbb5592368a4ed357737a0c2f7c037e8c78dde9e4864e...      2
8    8  b87c8b77909a35198fe8d44162fa0ca11607dbe03438b3...      3
9    9  6f4471459cd7232e9b8cc81315a11fabcce89edf152c8a...      0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   CID     80000 non-null  int64 
 1   Text    80000 non-null  object
 2   class   80000 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 1.8+ MB


In [5]:
data["class"].value_counts()

0    20048
1    20020
2    19970
3    19962
Name: class, dtype: int64

In [6]:
data['Text'].nunique()

79848

In [7]:
# data['Text Len'] = data['Text'].apply(lambda x : len(x))
# data['Text Len'].unique()

In [8]:
# data['Decimal'] = data['Text'].apply(lambda x : Decimal(int(x,16)))

In [9]:
df = data.drop(['CID'], axis=1)
df.head(10)

Text  class
0  3fa9e6ac4a36c66b8ca3887914c6c75b08dad9095f1d7a...      3
1  21b7f56f644f02d51ae82c9d50f69fad686319657712d4...      2
2  74203af11b8bbb1d31ac34e85f3076588fbbf2dcf1a4f7...      3
3  6b412e99f1dea02c124a90b5f2cf29496cb84f2b2b33a0...      1
4  5b84fb6fc7710b0e499394d9b406950d2436a118e2d867...      1
5  100c868cab4e21cbdd559c593b2bf54cdbf54c5ed0223f...      1
6  2b087feb3a6cff5c4811a7eff6e9024a761ef4b07f74f8...      3
7  4bbb5592368a4ed357737a0c2f7c037e8c78dde9e4864e...      2
8  b87c8b77909a35198fe8d44162fa0ca11607dbe03438b3...      3
9  6f4471459cd7232e9b8cc81315a11fabcce89edf152c8a...      0

In [10]:
# df['Decimal'].iloc[0]/(10**2405)

In [11]:
len(df['Text'].iloc[0])

2000

In [12]:
new_df = pd.DataFrame()

In [13]:
df['Text'].str[:5][:5]

0    3fa9e
1    21b7f
2    74203
3    6b412
4    5b84f
Name: Text, dtype: object

In [14]:
i = 0
while(i<=1997):
    new_df[str(i)+'_'+str(18+i)] = df['Text'].str[i:18+i].apply(lambda x : int(x,16))
    i += 20

In [15]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 100 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   0_18       80000 non-null  object
 1   20_38      80000 non-null  object
 2   40_58      80000 non-null  object
 3   60_78      80000 non-null  object
 4   80_98      80000 non-null  object
 5   100_118    80000 non-null  object
 6   120_138    80000 non-null  object
 7   140_158    80000 non-null  object
 8   160_178    80000 non-null  object
 9   180_198    80000 non-null  object
 10  200_218    80000 non-null  object
 11  220_238    80000 non-null  object
 12  240_258    80000 non-null  object
 13  260_278    80000 non-null  object
 14  280_298    80000 non-null  object
 15  300_318    80000 non-null  object
 16  320_338    80000 non-null  object
 17  340_358    80000 non-null  object
 18  360_378    80000 non-null  object
 19  380_398    80000 non-null  object
 20  400_418    80000 non-null  

In [24]:
new_df.to_pickle("./Data/pickled_NumSplit_data")
new_df.head()

0_18                   20_38                   40_58  \
0  1174387538715501554572  2517482010962150611673  1754564709374236950580   
1   621998177987263124762   822992570670981341977  2196519340388085896661   
2  2142144746208781606193   975974847057333566450  4457552558342076699884   
3  1978498476612417235986  2669441915855636838479   796930000458717630341   
4  1688236086242115784265  2745805293548292290209  4184557736668929965980   

                    60_78                   80_98                 100_118  \
0  2011423764916358737277  3309137269253643811931  4711661485283965323863   
1  2991729701945849933535  2469394833247028738503  2275916708419479016632   
2  1872097980463690968322   580469189005122871727  3374188637401805330623   
3   675995121474669380804  1887817792239957777733  3489660418368716797118   
4  4031324779903761756416  4272186438313128939265  1202654761555887596485   

                  120_138                 140_158                 160_178  \
0  2637194709035841391957  3071050719241934349966  2370558330344629999283   
1  2938560933347170988955  1958150446625914300659  2685293912844441057040   
2  2174173164555334174955  4155498018927972639395  2615121233526351839089   
3  2811467167865376361965  2074319928613950632475  4002501207155931332150   
4  4042256879128843153452  4543472916943652554101  1148943157007226580074   

                  180_198  ...               1820_1838  \
0   235626377026497747258  ...  3183371276587968459919   
1  2996471617131709540040  ...  2406875528055322590430   
2  3144794623269201099218  ...  4463765848231655546792   
3  1114525386803370395668  ...  3231679587936656833368   
4  2392806385667591983355  ...  4460034125568607306776   

                1840_1858               1860_1878               1880_1898  \
0  2388183159638022278621   689161408604333275123  2187161150259881967611   
1  1154588136794546935906  3474575477775397314140  1820855275549529229449   
2  4008441656227885382104  2092251949141543976095   995157118279836661976   
3  2695538525542696743636  1489286687957619373990  1347058672114247726353   
4   214384210614710818865  2841188869828719380750  2226610454999826938375   

                1900_1918               1920_1938               1940_1958  \
0  4132491864550671574633  3285388285830656705419    55438616183495358478   
1  1107492220024238346779  2346447455019759978982  3791574336824024490012   
2   482708942680299208057  2739500373841571502816  3714487502406291384077   
3  2502130643029872620105  1439749815282087310920  3058510048590310227472   
4  4318539874686689610205  3983161425418981312730   849185892951359646939   

                1960_1978               1980_1998 label  
0  3812627068413044718922  1316424663448686494011     3  
1  4133242031235392159836  4587152035580429674873     2  
2   504837335454242487987  1677320467643148316050     3  
3  3955910120191937894580  3748551112390420417919     1  
4  3199643796617003491667  3289582972247404910695     1  

[5 rows x 101 columns]

In [17]:
new_df['label'] = df['class']

/var/folders/s4/rbw51hr572v983ntn5czj87h0000gn/T/ipykernel_16825/4226739865.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df['label'] = df['class']


### Train Test Split

In [18]:
X = new_df.drop('label',axis=1)
y = new_df['label']

X_train, X_test, y_train, y_test = train_test_split(np.asarray(X).astype('float32'), np.asarray(y).astype('float32'), test_size=0.3, random_state=42)

y_train = tf.keras.utils.to_categorical(y_train, num_classes=4)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=4)

### DL Model

In [1]:
from keras.models import Sequential 
from keras.layers import Dense, GRU, LSTM

In [20]:
classifier = Sequential()

classifier.add(Dense(units = 500, kernel_initializer = 'uniform', activation = 'tanh', input_dim = 100))
classifier.add(Dense(units = 400, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 300, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 200, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 100, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 90, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 80, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 60, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 40, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 20, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 10, kernel_initializer = 'uniform', activation = 'tanh'))

classifier.add(Dense(units = 4, activation = 'softmax'))

In [21]:
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 50, epochs = 10)

y_pred = classifier.predict(X_test)
# y_pred = (y_pred > 0.5)


Epoch 1/10


2022-12-01 08:46:31.240268: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


1120/1120 [==============================] - 4s 3ms/step - loss: 1.3865 - accuracy: 0.2513
Epoch 2/10
1120/1120 [==============================] - 4s 3ms/step - loss: 1.3864 - accuracy: 0.2525
Epoch 3/10
1120/1120 [==============================] - 4s 3ms/step - loss: 1.3864 - accuracy: 0.2509
Epoch 4/10
1120/1120 [==============================] - 4s 3ms/step - loss: 1.3864 - accuracy: 0.2481
Epoch 5/10
1120/1120 [==============================] - 4s 3ms/step - loss: 1.3865 - accuracy: 0.2512
Epoch 6/10
1120/1120 [==============================] - 4s 3ms/step - loss: 1.3864 - accuracy: 0.2485
Epoch 7/10
1120/1120 [==============================] - 4s 3ms/step - loss: 1.3864 - accuracy: 0.2499
Epoch 8/10
1120/1120 [==============================] - 4s 3ms/step - loss: 1.3864 - accuracy: 0.2483
Epoch 9/10
1120/1120 [==============================] - 4s 3ms/step - loss: 1.3864 - accuracy: 0.2491
Epoch 10/10
750/750 [==============================] - 1s 782us/step


In [22]:
print(confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1)))

[[   0 6032    0    0]
 [   0 5950    0    0]
 [   0 5993    0    0]
 [   0 6025    0    0]]


In [23]:
y_pred

array([[0.2493248 , 0.2537506 , 0.2487127 , 0.24821195],
       [0.2493248 , 0.2537506 , 0.2487127 , 0.24821195],
       [0.2493248 , 0.2537506 , 0.2487127 , 0.24821195],
       ...,
       [0.2493248 , 0.2537506 , 0.2487127 , 0.24821195],
       [0.2493248 , 0.2537506 , 0.2487127 , 0.24821195],
       [0.2493248 , 0.2537506 , 0.2487127 , 0.24821195]], dtype=float32)