In [33]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

import tensorflow as tf 

from decimal import  Decimal
# import torch

In [2]:
# data.to_pickle("./Data/pickled_TrainingData")
# data = pd.read_csv("./Data/TrainingData.csv")
data = pd.read_pickle("./Data/pickled_TrainingData")
data.head(10)

CID                                               Text  class
0    0  3fa9e6ac4a36c66b8ca3887914c6c75b08dad9095f1d7a...      3
1    1  21b7f56f644f02d51ae82c9d50f69fad686319657712d4...      2
2    2  74203af11b8bbb1d31ac34e85f3076588fbbf2dcf1a4f7...      3
3    3  6b412e99f1dea02c124a90b5f2cf29496cb84f2b2b33a0...      1
4    4  5b84fb6fc7710b0e499394d9b406950d2436a118e2d867...      1
5    5  100c868cab4e21cbdd559c593b2bf54cdbf54c5ed0223f...      1
6    6  2b087feb3a6cff5c4811a7eff6e9024a761ef4b07f74f8...      3
7    7  4bbb5592368a4ed357737a0c2f7c037e8c78dde9e4864e...      2
8    8  b87c8b77909a35198fe8d44162fa0ca11607dbe03438b3...      3
9    9  6f4471459cd7232e9b8cc81315a11fabcce89edf152c8a...      0

In [3]:
df = data.drop(['CID'], axis=1)
df.head(10)

Text  class
0  3fa9e6ac4a36c66b8ca3887914c6c75b08dad9095f1d7a...      3
1  21b7f56f644f02d51ae82c9d50f69fad686319657712d4...      2
2  74203af11b8bbb1d31ac34e85f3076588fbbf2dcf1a4f7...      3
3  6b412e99f1dea02c124a90b5f2cf29496cb84f2b2b33a0...      1
4  5b84fb6fc7710b0e499394d9b406950d2436a118e2d867...      1
5  100c868cab4e21cbdd559c593b2bf54cdbf54c5ed0223f...      1
6  2b087feb3a6cff5c4811a7eff6e9024a761ef4b07f74f8...      3
7  4bbb5592368a4ed357737a0c2f7c037e8c78dde9e4864e...      2
8  b87c8b77909a35198fe8d44162fa0ca11607dbe03438b3...      3
9  6f4471459cd7232e9b8cc81315a11fabcce89edf152c8a...      0

### Generating images

In [4]:
import binascii
data = df['Text'].iloc[0]
data=data.strip()
data=data.replace(' ', '')
data=data.replace('\n', '')
data = binascii.a2b_hex(data)
with open('image.jpg', 'wb') as image_file:
    image_file.write(data)

In [56]:
def hexToRGB(hexadecimal):
    # convert a hex string to an array of RGB values
    h = hexadecimal.lstrip('#')
    return [int(h[i:i+2], 16) for i in (0, 2, 4)]

In [66]:
sample_imageRGB = []
i = 0
while(i<=1997):
    sample_imageRGB.append(hexToRGB(df['Text'].str[i:i+6].iloc[1000]))
    i += 6

In [67]:
imageRGB = np.asarray(sample_imageRGB).reshape((37,9,3))
img = Image.fromarray(imageRGB, 'RGB')
img

### Train Test Split

In [65]:
X = new_df.drop('label',axis=1)
y = new_df['label']

X_train, X_test, y_train, y_test = train_test_split(np.asarray(X).astype('float32'), np.asarray(y).astype('float32'), test_size=0.3, random_state=42)

y_train = tf.keras.utils.to_categorical(y_train, num_classes=4)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=4)

### DL Model

In [30]:
from keras.models import Sequential 
from keras.layers import Dense

In [101]:
classifier = Sequential()

classifier.add(Dense(units = 500, kernel_initializer = 'uniform', activation = 'tanh', input_dim = 100))
classifier.add(Dense(units = 400, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 300, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 200, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 100, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 90, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 80, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 60, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 40, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 20, kernel_initializer = 'uniform', activation = 'tanh'))
classifier.add(Dense(units = 10, kernel_initializer = 'uniform', activation = 'tanh'))

classifier.add(Dense(units = 4, activation = 'softmax'))

In [102]:
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 50, epochs = 10)

y_pred = classifier.predict(X_test)
# y_pred = (y_pred > 0.5)


Epoch 1/10
5600/5600 [==============================] - 12s 2ms/step - loss: 1.3867 - accuracy: 0.2501
Epoch 2/10
5600/5600 [==============================] - 11s 2ms/step - loss: 1.3865 - accuracy: 0.2528
Epoch 3/10
5600/5600 [==============================] - 11s 2ms/step - loss: 1.3865 - accuracy: 0.2486
Epoch 4/10
5600/5600 [==============================] - 11s 2ms/step - loss: 1.3865 - accuracy: 0.2511
Epoch 5/10
5600/5600 [==============================] - 11s 2ms/step - loss: 1.3865 - accuracy: 0.2518
Epoch 6/10
5600/5600 [==============================] - 11s 2ms/step - loss: 1.3866 - accuracy: 0.2477
Epoch 7/10
5600/5600 [==============================] - 11s 2ms/step - loss: 1.3865 - accuracy: 0.2499
Epoch 8/10
5600/5600 [==============================] - 11s 2ms/step - loss: 1.3865 - accuracy: 0.2515
Epoch 9/10
5600/5600 [==============================] - 11s 2ms/step - loss: 1.3866 - accuracy: 0.2506
Epoch 10/10
750/750 [==============================] - 1s 791us/step


In [107]:
print(confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1)))

[[   0 6032    0    0]
 [   0 5950    0    0]
 [   0 5993    0    0]
 [   0 6025    0    0]]


In [104]:
y_pred

array([[0.24794415, 0.25443932, 0.24746491, 0.25015157],
       [0.24794415, 0.25443932, 0.24746491, 0.25015157],
       [0.24794415, 0.25443932, 0.24746491, 0.25015157],
       ...,
       [0.24794415, 0.25443932, 0.24746491, 0.25015157],
       [0.24794415, 0.25443932, 0.24746491, 0.25015157],
       [0.24794415, 0.25443932, 0.24746491, 0.25015157]], dtype=float32)